### ISSUE TITLE
Research 4728, 4730 and 4734 Summit in the Nelle Peters Thematic Historic District

### ISSUE THREAD

**Issue by zmon** [codeforkansascity/teardown-tattler#11]
Document data where these addresses show up for further research. 

In June of 2015 neighborhood residents reported that these Plaza apartments on Summit had been vacated by all occupants. A subsequent search of city permit applications revealed utility cut-off and pre-demolition permits, indicating an intent for the buildings to be razed.
- [ ] Look at our [documented data](https://github.com/codeforkansascity/kc-open-data-library/wiki/List-of-datasets-and-locations)
  - [ ] Building Permit Listing
  - [ ] 311
  - [ ] Property Violations

**Comment by jalburty** [comment]
Looking for 4728, 4730 and 4734 Summit St in the Building Permit Listing, 311, and Property Violations data sets,
- There is nothing in the Building Permit Listing datasets, however we do not have data beyond March 2015.
- In the 311 dataset there is one open case for 4734 Summit with a Request Type of 'Property Violations'.
- In the Property Violations data set, which is apparently constantly updated, 4734 Summit does have several violations open:

Case Closed Date Days Open  Violation Description
4/20/2015        144    PAINTING NEEDED ON EXTERIOR WALL TRIM
4/20/2015        144    BROKEN SEWER CAUSED CAVE IN
4/20/2015        144    DANGER TO HEALTH OR SAFETY OF PUBLIC
4/20/2015        144    CAVE-IN ON PROPERTY
4/20/2015        144    CAVE-IN ON PROPERTY
4/20/2015        144    WINDOW ALLOWS ENTRY OF WEATHER.
4/20/2015        144    TREE LIMBS WITHIN 7.5 FEET OF SIDEWALK
4/20/2015        144    FAILURE TO REGISTER RENTAL DWELLING
4/20/2015        144    BROKEN PRIVATE SEWER LINE
4/20/2015        144    RANK WEEDS OR UNATTENDED GROWTH
4/20/2015        144    FAILURE TO REGISTER VACANT PROPERTY

To see the Demolition permits I suspect we just need Building Permits Listing data starting with April 2015.

**Comment by jalburty** [comment]
To create an alert it might be necessary for our Building Permit Listings data to be updated constantly like the Property Violations dataset apparently is.
